# Permalinks
permalink:        pretty

# Setup
title:            TJS_BSM
tagline:          'An Education in Hungary'
description:      'A weblog and travelogue for my semester in Hungary with the Budapest Semesters in Mathematics'
url:              http://tstirrat.me

author:
  name:           'Tanner Stirrat'
  url:            https://www.facebook.com/tstirrat

paginate:         5

# Custom vars
version:          0.1.0

highlighter: rouge

github:
  repo:           https://github.com/tstirrat15
