# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            TJS_BSM
tagline:          'An Education in Hungary'
description:      'A blog and travelogue for my semester in Hungary with the Budapest Semesters in Mathematics'
url:              http://tstirrat15.github.io

author:
  name:           'Tanner Stirrat'
  url:            https://www.facebook.com/tstirrat

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/tstirrat15